### ISSUE TITLE
 error while fetching mercari: <class 'requests.exceptions.JSONDecodeError'>

### ISSUE THREAD

**Issue by Emanyu94** [ThibautBremand/mercari-watchdog#24]
Hi
The app worked great for a week then suddenly I am getting the following error 
"error while fetching mercari: <class 'requests.exceptions.JSONDecodeError'>"
I tried reinstalling but not to avail 

C:\Users\Eman\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Starting mercari-watchdog...
2023-07-10 23:55:05 INFO     Handling keywords Item Name
2023-07-10 23:55:06 ERROR    error while fetching mercari: <class 'requests.exceptions.JSONDecodeError'>
2023-07-10 23:55:06 INFO     Found 0 new items for keywords Item Name
2023-07-10 23:55:08 INFO     Sending messages to Telegram
2023-07-10 23:55:15 INFO     Messages sent!
2023-07-10 23:55:15 INFO     Writing cache...
2023-07-10 23:55:15 INFO     Cache written!

I would be grateful for a solution

**Comment by Emanyu94** [comment]
Seems like the Mercari API got updated. Could you update the code to use the newly updated version of @marvinody's mercari wrapper?

**Comment by ThibautBremand** [comment]
Hey @Emanyu94 , thanks for reaching out. I'll look at this as soon as possible 👍

**Comment by ThibautBremand** [comment]
@Emanyu94 I have merged a fix, can you try? I cannot properly test for the moment unfortunately, but locally the code seems to be working.

**Comment by Emanyu94** [comment]
> @Emanyu94 I have merged a fix, can you try? I cannot properly test for the moment unfortunately, but locally the code seems to be working.
> 
> Please refresh the submodule `git submodule update --init --recursive`

Thank you for your quick reply. Unfortunately, in the new version the following error is being shown in the console on each update:

`2023-07-12 16:01:16 ERROR    error while fetching mercari: <class 'requests.exceptions.HTTPError'>`

**Comment by Emanyu94** [comment]
Hi again.
I just checked again today and it was indeed caused by my mistake, it works well now.
Sorry and once again thank you for the update!

All the best!

**Comment by bthibaut** [comment]
Hey, I'm glad it works :) 
I'm closing the issue.
All the best!
